name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
